# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0002af2d2fb36cd4bc7c86d3da4ed4411085480ad77fe7edd9ecee466540281d2a3b9af6620f25dac2491c7b2cb78d6a117139b2ff555e9e7c9f90286c11136a

test:
  secret_key_base: ba6c9aadcdc3ac239034577a615962b719d45af265d7aee349eb283fed42e7c8c72a6d1552b9ef6aefcbdb7f0387d18c85138bb5c7cfda36521fdff284555d56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
